workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    glean-api-specs:
        inputs:
            - location: generated_specs/client_rest.yaml
            - location: generated_specs/indexing.yaml
        overlays:
            - location: overlays/speakeasy-modifications-overlay.yaml
            - location: overlays/info-name-overlay.yaml
        output: overlayed_specs/glean-merged-spec.yaml
        registry:
            location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs
    glean-client-combined-spec:
        inputs:
            - location: generated_specs/client_rest.yaml
        overlays:
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-typescript-code-samples
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-python-code-samples
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-java-code-samples
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-go-code-samples
        output: glean-client-combined-spec.yaml
        registry:
            location: registry.speakeasyapi.dev/glean-el2/sdk/glean-client-combined-spec
    glean-index-combined-spec:
        inputs:
            - location: generated_specs/indexing.yaml
        overlays:
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-typescript-code-samples
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-python-code-samples
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-java-code-samples
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-go-code-samples
        output: glean-index-combined-spec.yaml
        registry:
            location: registry.speakeasyapi.dev/glean-el2/sdk/glean-index-combined-spec
targets: {}
