workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    glean-api-specs:
        inputs:
            - location: generated_specs/client_rest.yaml
            - location: generated_specs/indexing.yaml
        overlays:
            - location: overlays/speakeasy-modifications-overlay.yaml
            - location: overlays/chat-endpoint-fixes-overlay.yaml
            - location: overlays/info-name-overlay.yaml
            - location: overlays/add-chat-stream-overlay.yaml
            - location: overlays/strip-headers-overlay.yaml
        output: overlayed_specs/glean-merged-spec.yaml
        registry:
            location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs
    glean-client-merged-code-samples-spec:
        inputs:
            - location: generated_specs/client_rest.yaml
        overlays:
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-python-code-samples
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-typescript-code-samples
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-go-code-samples
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-java-code-samples
        output: merged_code_samples_specs/glean-client-merged-code-samples-spec.yaml
        registry:
            location: registry.speakeasyapi.dev/glean-el2/sdk/glean-client-merged-code-samples-spec
    glean-index-merged-code-samples-spec:
        inputs:
            - location: generated_specs/indexing.yaml
        overlays:
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-python-code-samples
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-typescript-code-samples
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-java-code-samples
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-go-code-samples
        output: merged_code_samples_specs/glean-index-merged-code-samples-spec.yaml
        registry:
            location: registry.speakeasyapi.dev/glean-el2/sdk/glean-index-merged-code-samples-spec
targets: {}
