name: 'Setup Speakeasy CLI'
description: 'Install Speakeasy CLI via Homebrew'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Speakeasy CLI
      run: curl -fsSL https://go.speakeasy.com/cli-install.sh | sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
