name: Update dist

on:
  push:
    branches: [main]

jobs:
  update-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up mise
        uses: jdx/mise-action@v2
        with:
          cache: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build dist
        run: pnpm run build

      - name: Commit and push dist changes
        uses: ./.github/actions/git-commit
        with:
          commit_message: "chore: update dist/ directory"
          file_patterns: "dist/"
          github_token: ${{ secrets.GITHUB_TOKEN }}
